Disable ZSTD support in GCC due to linker errors (GCC 12.x)
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
Undefined symbols for architecture arm64:
  "_ZSTD_compress", referenced from:
      lto_end_compression(lto_compression_stream*) in libbackend.a(lto-compress.o)
  "_ZSTD_compressBound", referenced from:
      lto_end_compression(lto_compression_stream*) in libbackend.a(lto-compress.o)
  "_ZSTD_decompress", referenced from:
      lto_end_uncompression(lto_compression_stream*, lto_compression) in libbackend.a(lto-compress.o)
  "_ZSTD_getErrorName", referenced from:
      lto_end_compression(lto_compression_stream*) in libbackend.a(lto-compress.o)
      lto_end_uncompression(lto_compression_stream*, lto_compression) in libbackend.a(lto-compress.o)
  "_ZSTD_getFrameContentSize", referenced from:
      lto_end_uncompression(lto_compression_stream*, lto_compression) in libbackend.a(lto-compress.o)
  "_ZSTD_isError", referenced from:
      lto_end_compression(lto_compression_stream*) in libbackend.a(lto-compress.o)
      lto_end_uncompression(lto_compression_stream*, lto_compression) in libbackend.a(lto-compress.o)
  "_ZSTD_maxCLevel", referenced from:
      lto_end_compression(lto_compression_stream*) in libbackend.a(lto-compress.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)